chat/urls.py
from django.urls import path
from . import views


app_name="chat"
urlpatterns = [
    path('', views.home, name='home'),
    path('getMessages/<str:room>/', views.getMessages, name="getMessages"),
    path('<str:room>/<str:username>/', views.room, name="room"),
    path('checkview/', views.checkview, name='checkview'),
    path('send/', views.send, name='send'),
]

djangochat/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls', namespace='chat'))
]

chat/models.py
from django.db import models
from django.db.models.expressions import Value
from datetime import datetime

# Create your models here.
class Room(models.Model):
    name = models.CharField(max_length=1000)

    def __str__(self):
        return f"{self.name}"


class Messages(models.Model):
    value = models.CharField(max_length=100000)
    date = models.DateTimeField(auto_now_add=True)
    user = models.CharField(max_length=10000)
    room = models.CharField(max_length=100000)

    def __str__(self):
        return f"{self.room} by {self.user}"

chat/views.py
from django.http.response import HttpResponse, JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from chat.models import Messages, Room

# Create your views here.

def home(request):
    return render(request, 'chat/home.html')

def room(request, **kwargs):
    room = str(kwargs['room'])
    print(room)
    username = kwargs['username']
    room_detail = Room.objects.get(name=room)
    return render(request, 'chat/room.html', {'room':room, 'username':username, 'room_details':room_detail})

def checkview(request):
    # if request.method == 'POST':
    room = request.POST['room_name']
    username = request.POST['username']
    print(room)
    print(Room.objects.filter(name=room).exists())
    if Room.objects.filter(name=room).exists():
        return redirect(reverse('chat:room', kwargs= {'room':room, 'username':username}))
    else:
        new_room = Room.objects.create(name=room)
        new_room.save()
        print("craeted")   
        return redirect(reverse('chat:room', kwargs={'room': room, 'username': username}))
    

def send(request):
    message = request.POST['message']
    print(message)
    username = request.POST['username']
    room_id = request.POST['room_id']

    new_message = Messages.objects.create(
        value=message,
        user=username,
        room=room_id
    )

    new_message.save
    print("Good here")
    return HttpResponse("Message sent successfully")


def getMessages(request,  **kwargs):
    print("++++++++++++++++++++++++++++++++++++++++++++++++++++")
    room = str(kwargs['room'])
    room_details = Room.objects.get(name=room)
    messages = Messages.objects.filter(room=room_details.id)
    return JsonResponse({'messages': list(messages.values())})

templates/chat/home.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
  margin: 0 auto;
  max-width: 800px;
  padding: 0 20px;
}

.container {
  border: 2px solid #dedede;
  background-color: #f1f1f1;
  border-radius: 5px;
  padding: 10px;
  margin: 10px 0;
}

.darker {
  border-color: #ccc;
  background-color: #ddd;
}

.container::after {
  content: "";
  clear: both;
  display: table;
}

.container img {
  float: left;
  max-width: 60px;
  width: 100%;
  margin-right: 20px;
  border-radius: 50%;
}

.container img.right {
  float: right;
  margin-left: 20px;
  margin-right:0;
}

.time-right {
  float: right;
  color: #aaa;
}

.time-left {
  float: left;
  color: #999;
}
</style>
</head>
<body>

<div align="center">
    <h2>Django Chat</h2>
</div>


<div class="container">
    <style>
    input[type=text], select {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    }

    input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    }

    input[type=submit]:hover {
    background-color: #45a049;
    }

    div {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
    }
    </style>

  <form id="post-form" method="POST" action="checkview/">
        {% csrf_token %}
        <label>Room Name</label>
        <input type="text" name="room_name" id="room_name" width="100px" />
        <label>Username</label>
        <input type="text" name="username" id="username" width="100px" />
        <input type="submit" value="Enter Room">
    </form>
</div>


</body>


</html>

templates/chat/room.html
<!DOCTYPE html>
<html>

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
        body {
            margin: 0 auto;
            max-width: 800px;
            padding: 0 20px;
        }

        .container {
            border: 2px solid #dedede;
            background-color: #f1f1f1;
            border-radius: 5px;
            padding: 10px;
            margin: 10px 0;
        }

        .darker {
            border-color: #ccc;
            background-color: #ddd;
        }

        .container::after {
            content: "";
            clear: both;
            display: table;
        }

        .container img {
            float: left;
            max-width: 60px;
            width: 100%;
            margin-right: 20px;
            border-radius: 50%;
        }

        .container img.right {
            float: right;
            margin-left: 20px;
            margin-right: 0;
        }

        .time-right {
            float: right;
            color: #aaa;
        }

        .time-left {
            float: left;
            color: #999;
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js" integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8=" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"></script>
</head>

<body>

    <h2>{{room}} - {{ username }}-Chat</h2>

    <div id="display">
        
        {% comment %} <div class="container darker">
  <b>Tom</b><p>Hello Everyone, How Are You Guys Doing?</p>
  <span class="time-left">20th, April 2021</span>
</div>  {% endcomment %}

</div>     
<script>
    $(document).ready(function () {

        setInterval(function () {
            $.ajax({
                type: 'GET',
                url: "{% url 'chat:getMessages' room %}",
                success: function (response) {
                    console.log(response);
                    $("#display").empty();
                    for (var key in response.messages) {
                        var temp = "<div class='container darker'><b>" + response.messages[key].user + "</b><p>" + response.messages[key].value + "</p><span class='time-left'>" + response.messages[key].date + "</span></div>";
                        $("#display").append(temp);
                    }
                },
                error: function (response) {
                    alert('An error occured')
                }
            });
        }, 1000);
    })
</script> 

    <div class="container">
        <style>
            input[type=text],
            select {
                width: 100%;
                padding: 12px 20px;
                margin: 8px 0;
                display: inline-block;
                border: 1px solid #ccc;
                border-radius: 4px;
                box-sizing: border-box;
            }

            input[type=submit] {
                width: 100%;
                background-color: #4CAF50;
                color: white;
                padding: 14px 20px;
                margin: 8px 0;
                border: none;
                border-radius: 4px;
                cursor: pointer;
            }

            input[type=submit]:hover {
                background-color: #45a049;
            }

            div {
                border-radius: 5px;
                background-color: #f2f2f2;
                padding: 20px;
            }
        </style>

        <form id="post-form">
            {% csrf_token %}
            <input type="hidden" name="username" id="username" value="{{username}}" />
            <input type="hidden" name="room_id" id="room_id" value="{{room_details.id}}" />
            <input type="text" name="message" id="message" width="100px" />
            <input type="submit" value="Send">
        </form>
    </div>


</body>

<script type="text/javascript">
    $(document).on('submit', '#post-form', function (e) {
        e.preventDefault();

        $.ajax({
            type: 'POST',
            url: "{% url 'chat:send' %}",
            data: {
                username: $('#username').val(),
                room_id: $('#room_id').val(),
                message: $('#message').val(),
                csrfmiddlewaretoken: $('input[name=csrfmiddlewaretoken]').val(),
            },
            success: function (data) {
                alert(data)
            }
        });
        document.getElementById('message').value = ''
    });
</script>

</html>